services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: final_project_db
      PGDATA: /var/lib/postgresql/data/pgdata15
    networks:
      - bootcamp-network
    ports:
      - "5532:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"

  redis:
    image: redis:7
    container_name: redis-container
    networks:
      - bootcamp-network
    ports:
      - "6479:6379"
    volumes:
      - "./redis_data:/data"

  data-provider-app:
    image: project-data-provider:0.0.1
    container_name: data-provider-app
    networks:
      - bootcamp-network
    ports:
      - "8171:8071"
      
  stock-data-app:
    image: project-stock-data:0.0.1
    container_name: stock-data-app
    networks:
      - bootcamp-network
    ports:
      - "8172:8072"

  heatmap-ui-app:
    image: project-heatmap-ui:0.0.1
    container_name: heatmap-ui-app
    networks:
      - bootcamp-network
    ports:
      - "8173:8073"

volumes:
  redis_data:

networks:
  bootcamp-network:
    driver: bridge